<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Uppgift2</RootNamespace>
    <AssemblyName>ConsoleApplication</AssemblyName>
    <LangVersion>latest</LangVersion>
    <StartupObject>Uppgift2.Uppgift2Program</StartupObject>
  </PropertyGroup>
</Project>
